# Generated by Django 5.2.1 on 2026-05-22 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='documentrenewal',
            options={'ordering': ['-renewal_requested_on']},
        ),
        migrations.AlterModelOptions(
            name='inappnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='meetinglog',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='virtualmeeting',
            options={'ordering': ['-scheduled_on']},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AddField(
            model_name='document',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_department_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('DOCUMENT_RENEWAL', 'Document Renewal'), ('MEETING_REQUEST', 'Meeting Request'), ('FAILED_BIOMETRIC', 'Failed Biometric Verification'), ('FAILED_LOGIN', 'Failed Login'), ('DOCUMENT_SUBMISSION', 'Document Submission'), ('DOCUMENT_APPROVAL', 'Document Approval'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('MEETING_ENDED', 'Meeting Ended')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='enrolled_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='biometric_data',
            field=models.JSONField(blank=True, help_text='Stores biometric metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('id', 'ID Card'), ('passport', 'Passport'), ('birth_certificate', 'Birth Certificate'), ('drivers_license', "Driver's License"), ('marriage_certificate', 'Marriage Certificate'), ('divorce_decree', 'Divorce Decree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentrenewal',
            name='renewal_requested_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documentrenewal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_renewals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetinglog',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('APP', 'App')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smartid',
            name='issued_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='smartid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='Indicates if admin has activated this user.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional link to parent user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='virtualmeeting',
            name='scheduled_on',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='virtualmeeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='virtualmeeting',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_virtual_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'action'], name='core_activi_user_id_f3082a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='core_docume_documen_5649ee_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_admin_approved', 'is_department_approved'], name='core_docume_is_admi_bb1146_idx'),
        ),
        migrations.AddIndex(
            model_name='meetinglog',
            index=models.Index(fields=['user', 'worker'], name='core_meetin_user_id_0b6d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_admin'], name='core_user_is_admi_7502e4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_activated'], name='core_user_is_acti_65749d_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['department'], name='core_worker_departm_0ae903_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['active'], name='core_worker_active_bfd4f7_idx'),
        ),
    ]
