# Generated by Django 5.2.3 on 2026-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_hash',
            field=models.CharField(blank=True, help_text='HMAC-SHA256 integrity hash.', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=False, help_text='True after OTP verified this session.'),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, help_text='TOTP secret for 2FA OTP generation.', max_length=64),
        ),
    ]
